spring:
    application:
        name: ace-monitor

server:
    port: 8764 #启动端口

eureka:
     instance:
        preferIpAddress: true
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/


